project_id = "qtstzkyycjldlwgiqsgh"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.request-setup-link]
    verify_jwt = false
  [functions.send-invite]
    verify_jwt = true
