// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-companies.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
function sb(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_companies_default = defineTool({
  name: "list_companies",
  title: "List companies",
  description: "List the portfolio companies the signed-in Intrinsic user has access to (via licensee_companies).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb(ctx).from("companies").select("id, name, created_at").order("name", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { companies: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-company-config.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_company_config_default = defineTool2({
  name: "get_company_config",
  title: "Get company config",
  description: "Fetch the full v2 financial-model config JSON for one company by id. Access is enforced by RLS.",
  inputSchema: {
    company_id: z.string().min(1).describe("Company id, e.g. co_xxxxxxxx")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb2(ctx).from("companies").select("id, name, config, created_at, updated_at").eq("id", company_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "Company not found or not accessible." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { company: data }
    };
  }
});

// src/lib/mcp/tools/list-referrals.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_referrals_default = defineTool3({
  name: "list_referrals",
  title: "List referrals",
  description: "List referrals for a company. Does NOT include SSN. Access is enforced by RLS on the referrals table.",
  inputSchema: {
    company_id: z2.string().min(1).describe("Company id to scope the referrals to."),
    stage: z2.string().optional().describe("Optional pipeline stage filter (e.g. 'inquiry', 'accepted', 'enrolled')."),
    limit: z2.number().int().optional().describe("Max rows to return. Defaults to 50, capped at 200.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company_id, stage, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const cap = Math.min(Math.max(limit ?? 50, 1), 200);
    let q = sb3(ctx).from("referrals").select(
      "id, company_id, first_name, last_name, preferred_name, stage, outcome, service_level, pay_source, city, county, region, state, is_minor, stage_entered_at, last_activity_at, created_at"
    ).eq("company_id", company_id).order("last_activity_at", { ascending: false }).limit(cap);
    if (stage) q = q.eq("stage", stage);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [
        { type: "text", text: `Found ${data?.length ?? 0} referrals.` },
        { type: "text", text: JSON.stringify(data ?? [], null, 2) }
      ],
      structuredContent: { referrals: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qtstzkyycjldlwgiqsgh";
var mcp_default = defineMcp({
  name: "intrinsic-mcp",
  title: "Intrinsic",
  version: "0.1.0",
  instructions: "Read-only access to Intrinsic's HCBS financial modeling data. Use `list_companies` to discover the companies you can see, `get_company_config` to read a company's full v2 config JSON, and `list_referrals` to browse a company's referral pipeline. All access is scoped by the signed-in user's licensee assignments (RLS).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_companies_default, get_company_config_default, list_referrals_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
